# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ea089a82c4cebeb9e8dd390eabdf4f8b"
application_url = "https://similar-rj-titanium-headed.trycloudflare.com"
embedded = true
name = "epik-gearlab-app"
handle = "epik-gearlab-app"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://similar-rj-titanium-headed.trycloudflare.com/auth/callback",
  "https://similar-rj-titanium-headed.trycloudflare.com/auth/shopify/callback",
  "https://similar-rj-titanium-headed.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
